# grafana_deployment.yaml
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  ingress:
    enabled: true
  dashboardLabelSelector:
    - matchLabels:
        grafana_dashboard: "1"
